import { Proposal } from '@lib/types/proposals'

export const submittedProposals: Proposal[] = [
  {
    id: 4,
    date: 'Mar 5, 2025',
    timeAgo: '13 hours ago',
    hasBoosted: true,
    title: 'Corporate Strategy Planning for Tech Startup',
    profile: 'Business Strategy',
    viewedByClient: false,
    amount: '$1,800',
    status: 'Submitted',
    clientName: 'Innovate Labs',
    clientLocation: 'Germany',
    bidAmount: 1800,
    coverLetter:
      "Having helped multiple tech startups define their corporate strategy, I'm excited to bring my expertise to your growing business.",
    skills: [
      'Corporate Strategy',
      'Tech Startups',
      'Market Analysis',
      'Growth Planning',
    ],
    lastActivity: 'Proposal submitted 13 hours ago',
    projectDuration: '1-2 months',
    proposalViews: 0,
    competingProposals: 7,
    interviewRate: null,
    clientRating: 4.6,
    clientSpend: '$12k+',
    clientHires: 6,
  },
  {
    id: 5,
    date: 'Mar 4, 2025',
    timeAgo: 'yesterday',
    hasBoosted: true,
    title: 'Market Entry Strategy for Healthcare Innovation',
    profile: 'Healthcare Consulting',
    viewedByClient: false,
    amount: '$3,200',
    status: 'Submitted',
    clientName: 'MedTech Innovations',
    clientLocation: 'Australia',
    bidAmount: 3200,
    coverLetter:
      'With my background in healthcare market entry strategies across 5 countries, I can provide the comprehensive approach you need for your innovative solution.',
    skills: [
      'Healthcare Industry',
      'Market Entry',
      'Regulatory Strategy',
      'Commercialization',
    ],
    lastActivity: 'Proposal submitted yesterday',
    projectDuration: '3 months',
    proposalViews: 0,
    competingProposals: 9,
    interviewRate: null,
    clientRating: 4.9,
    clientSpend: '$45k+',
    clientHires: 14,
  },
  {
    id: 6,
    date: 'Feb 28, 2025',
    timeAgo: '5 days ago',
    hasBoosted: false,
    title: 'Supply Chain Management Consultancy',
    profile: 'Operations Consulting',
    viewedByClient: true,
    amount: '$1,500',
    status: 'Viewed',
    clientName: 'Global Manufacturing Co.',
    clientLocation: 'Japan',
    bidAmount: 1500,
    coverLetter:
      "I've successfully optimized supply chains for manufacturing companies across Asia and North America, resulting in average cost savings of 18% and 30% reduced lead times.",
    skills: [
      'Supply Chain Optimization',
      'Logistics',
      'Inventory Management',
      'Operations',
    ],
    lastActivity: 'Client viewed your proposal 2 days ago',
    projectDuration: '6-8 weeks',
    proposalViews: 1,
    competingProposals: 15,
    interviewRate: null,
    clientRating: 4.5,
    clientSpend: '$28k+',
    clientHires: 9,
  },
]

export default submittedProposals
