import { Proposal } from '@lib/types/proposals'

const activeProposals: Proposal[] = [
  {
    id: 1,
    date: 'Mar 4, 2025',
    timeAgo: 'yesterday',
    hasBoosted: true,
    title: 'Financial Advisory Services for Technology Scale-up',
    profile: 'Business Consulting',
    amount: '﷼1,250',
    status: 'In review',
    clientName: 'TechGrowth Solutions',
    clientLocation: 'United States',
    bidAmount: 1250,
    coverLetter:
      "I'm excited about the opportunity to provide financial advisory services for your technology scale-up. My experience working with SaaS and fintech companies positions me well to support your growth objectives.",
    skills: [
      'Financial Analysis',
      'Business Strategy',
      'Growth Planning',
      'Tech Industry',
    ],
    lastActivity: 'Client viewed your proposal 2 hours ago',
    projectDuration: '2-3 months',
    proposalViews: 3,
    competingProposals: 12,
    interviewRate: '25%',
    clientRating: 4.9,
    clientSpend: '﷼15k+',
    clientHires: 8,
  },
  {
    id: 2,
    date: 'Feb 5, 2025',
    timeAgo: '4 weeks ago',
    hasBoosted: false,
    title: 'Strategic Business Transformation & Digital Growth Plan',
    profile: 'General Profile',
    amount: '﷼2,500',
    status: 'Interviewing',
    clientName: 'Nova Enterprises',
    clientLocation: 'United Kingdom',
    bidAmount: 2500,
    coverLetter:
      "Having led digital transformation initiatives for over 10 companies in varied industries, I'm confident I can deliver the strategic growth plan you're looking for.",
    skills: [
      'Digital Strategy',
      'Business Transformation',
      'Strategic Planning',
      'Change Management',
    ],
    lastActivity: 'Message from client 1 day ago',
    projectDuration: '3-4 months',
    proposalViews: 5,
    competingProposals: 18,
    interviewRate: '30%',
    clientRating: 4.7,
    clientSpend: '﷼32k+',
    clientHires: 12,
  },
  {
    id: 3,
    date: 'Feb 4, 2025',
    timeAgo: '4 weeks ago',
    hasBoosted: false,
    title: 'Financial Model Development for SaaS Enterprise',
    profile: 'Finance Consulting',
    amount: '﷼850',
    status: 'In review',
    clientName: 'CloudScale Solutions',
    clientLocation: 'Canada',
    bidAmount: 850,
    coverLetter:
      "As a financial consultant with deep SaaS experience, I've developed 20+ financial models for SaaS companies that have directly informed strategic decisions and funding rounds.",
    skills: ['Financial Modeling', 'SaaS Metrics', 'Forecasting', 'Valuation'],
    lastActivity: 'Client viewed your profile yesterday',
    projectDuration: '2 weeks',
    proposalViews: 2,
    competingProposals: 8,
    interviewRate: '15%',
    clientRating: 4.8,
    clientSpend: '﷼8k+',
    clientHires: 5,
  },
]

export default activeProposals
